# -*- coding: utf-8 -*-
"""Texty rozhraní. Klíč -> (English, Čeština).

Přidání dalšího jazyka: rozšířit JAZYKY a doplnit třetí položku do každé n-tice.
Zástupné symboly {0}, {1} ... se plní přes T("klic", hodnota).
"""

JAZYKY = {"en": "English", "cs": "Čeština"}
PORADI = ("en", "cs")

_aktualni = "en"


def nastav_jazyk(kod: str):
    global _aktualni
    if kod in JAZYKY:
        _aktualni = kod


def aktualni_jazyk() -> str:
    return _aktualni


def T(klic: str, *args) -> str:
    polozka = TEXTY.get(klic)
    if polozka is None:
        return klic
    sablona = polozka[PORADI.index(_aktualni)]
    try:
        return sablona.format(*args) if args else sablona
    except (IndexError, KeyError):
        return sablona


TEXTY = {
    # ---------------- Okno a sekce ----------------
    "app_nazev":        ("Audiobookery", "Audiobookery"),
    "znacka":           ("audiobookery", "audiobookery"),
    "podtitul":         ("chatterbox · v{0}", "chatterbox · v{0}"),

    # ---------------- Tlačítka ----------------
    "btn_vybrat":       ("browse", "vybrat"),
    "btn_start":        ("Start conversion", "Spustit převod"),
    "btn_pauza":        ("Pause", "Pauza"),
    "btn_pokracovat":   ("Resume", "Pokračovat"),
    "dlg_zdroj_pryc":   ("The source file is gone:\n{0}\n\nWithout it the conversion cannot continue.",
                         "Zdrojový soubor zmizel:\n{0}\n\nBez něj nelze v převodu pokračovat."),
    "log_obnoveno":     ("Settings restored from the interrupted run: {0}",
                         "Nastavení obnoveno z přerušeného běhu: {0}"),
    "btn_zastavit":     ("Stop", "Zastavit"),
    "btn_otevrit":      ("Open output", "Otevřít výstup"),

    # ---------------- Popisky ----------------
    "lab_expresivita":  ("expressiveness", "expresivita"),
    "lab_cfg":          ("cfg / pace", "cfg / tempo"),
    "lab_teplota":      ("temperature", "teplota"),
    "lab_znaku":        ("chars per block", "znaků na blok"),
    "lab_pauza_ms":     ("gap (ms)", "pauza (ms)"),
    "lab_min_p":        ("min_p (tail cut)", "min_p (ořez ocasu)"),
    "lab_seed":         ("seed", "seed"),
    "lab_zarizeni":     ("device", "zařízení"),
    "lab_jazyk_textu":  ("Book language", "Jazyk knihy"),
    "jaz_zakladni":     ("built into the base model, nothing to download",
                         "je v základním modelu, nic se nestahuje"),
    "jaz_stazeno_gb":   ("model downloaded · {0:.1f} GB", "model stažen · {0:.1f} GB"),
    "jaz_stahne":       ("downloads {0:.1f} GB on first use",
                         "při prvním použití stáhne {0:.1f} GB"),
    "jaz_neovereno":    ("community model, untested", "komunitní model, neověřený"),
    "jaz_bez_tokenu":   ("tokenizer has no token for this language",
                         "tokenizer pro tento jazyk nemá token"),
    "jaz_gated":        ("needs a Hugging Face login", "vyžaduje přihlášení k Hugging Face"),
    "lab_orez":         ("trim block edges", "oříznout okraje bloku"),
    "lab_lupance":      ("remove clicks", "odstranit lupance"),
    "lab_rychly_dekoder": ("fast decoder", "rychlý dekodér"),
    "dlg_oprava":       ("Fix a passage", "Oprava úseku"),
    "oprava_popis":     ("Find the spot by its time, generate the block again and swap it into the file. "
                         "The text can be edited before generating - it is read exactly as written.",
                         "Najděte místo podle času, vygenerujte blok znovu a vyměňte ho v souboru. "
                         "Text jde před generováním upravit - přečte se přesně tak, jak je napsaný."),
    "lab_soubor":       ("file", "soubor"),
    "lab_cas":          ("time", "čas"),
    "btn_najit":        ("find", "najít"),
    "oprava_blok":      ("block {0} · {1} – {2}", "blok {0} · {1} – {2}"),
    "btn_prehrat_puvodni": ("play original", "přehrát původní"),
    "btn_generovat_znovu": ("generate again", "vygenerovat znovu"),
    "btn_prehrat_novy": ("play new", "přehrát nový"),
    "btn_nahradit":     ("replace in file", "nahradit v souboru"),
    "btn_zavrit":       ("close", "zavřít"),
    "oprava_zadny_soubor": ("No audio files in {0}.", "Ve složce {0} nejsou žádné zvukové soubory."),
    "oprava_bez_mapy":  ("This file has no complete block map - all or part of it was made before version 1.11. "
                         "Load the same book with the same settings and the blocks will be found from the pauses.",
                         "K souboru chybí úplná mapa bloků - celý nebo jeho část vznikl před verzí 1.11. "
                         "Načtěte stejnou knihu se stejným nastavením a bloky se dohledají podle pauz."),
    "oprava_nesedi":    ("The recording does not match the loaded book ({0} blocks in the book, {1} in the "
                         "recording). Check the book, the characters per block and the pause.",
                         "Nahrávka nesedí s načtenou knihou ({0} bloků v knize, {1} v nahrávce). "
                         "Zkontrolujte knihu, znaky na blok a pauzu."),
    "oprava_dohledano": ("Blocks found from the pauses ({0}). The current voice settings will be used.",
                         "Bloky dohledány podle pauz ({0}). Použije se aktuální nastavení hlasu."),
    "oprava_nacteno":   ("{0} blocks. Enter a time and press find.",
                         "{0} bloků. Zadejte čas a stiskněte najít."),
    "oprava_spatny_cas": ("Enter the time as mm:ss or h:mm:ss.", "Zadejte čas jako mm:ss nebo h:mm:ss."),
    "oprava_mimo":      ("That time is past the end of the file.", "Ten čas je za koncem souboru."),
    "oprava_generuji":  ("Generating...", "Generuji..."),
    "oprava_vygenerovano": ("New take: {0:.1f} s (the original has {1:.1f} s).",
                            "Nový pokus: {0:.1f} s (původní má {1:.1f} s)."),
    "oprava_nevyslo":   ("The block could not be generated.", "Blok se nepodařilo vygenerovat."),
    "oprava_nahrazuji": ("Replacing...", "Nahrazuji..."),
    "oprava_nahrazeno": ("Replaced. The previous version is backed up in {0}",
                         "Nahrazeno. Předchozí verze je zazálohovaná v {0}"),
    "oprava_mp3_selhal": ("MP3 conversion failed, the file was left untouched.",
                          "Převod do MP3 selhal, soubor zůstal beze změny."),
    "oprava_chyba":     ("Failed: {0}", "Nepodařilo se: {0}"),
    "log_oprava":       ("Passage fixed: {0}, block {1}.", "Opraven úsek: {0}, blok {1}."),
    "lab_kontrola_asr": ("transcription check", "kontrola přepisem"),
    "hint_asr_stahne":  ("picks the best attempt of a suspicious block · downloads {0:.1f} GB on first use",
                         "u podezřelého bloku vybere nejlepší pokus · poprvé stáhne {0:.1f} GB"),
    "hint_asr_stazeno": ("picks the best attempt of a suspicious block · already downloaded",
                         "u podezřelého bloku vybere nejlepší pokus · staženo"),
    "hint_hlas":        ("without a reference recording the model's default english voice is used",
                         "bez referenční nahrávky se použije výchozí anglický hlas modelu"),

    # ---------------- Okno podle návrhu 1.12 ----------------
    "stitek_nastaveni": ("SETTINGS", "NASTAVENÍ"),
    "stitek_zdroj":     ("SOURCE", "ZDROJ"),
    "stitek_hlas":      ("VOICE", "HLAS"),
    "stitek_vystup":    ("OUTPUT", "VÝSTUP"),
    "stitek_rozdelane": ("UNFINISHED CONVERSIONS", "ROZDĚLANÉ PŘEVODY"),
    "stitek_log":       ("ACTIVITY", "PODROBNÝ PRŮBĚH"),
    "stitek_kapitoly":  ("CHAPTERS", "KAPITOLY"),
    "lab_kniha":        ("Book", "Kniha"),
    "lab_nahravka":     ("Voice recording", "Nahrávka hlasu"),
    "lab_zkusebni_veta": ("Test sentence", "Zkušební věta"),
    "lab_nazev_souboru": ("File name", "Název souboru"),
    "btn_zmenit":       ("Change", "Změnit"),
    "btn_prehrat":      ("Play", "Přehrát"),
    "zadna_kniha":      ("no book selected", "není vybrána kniha"),
    "vychozi_hlas":     ("model's default voice", "výchozí hlas modelu"),
    "chip_obalka":      ("cover", "obálka"),
    "chip_lupance":     ("no clicks", "bez lupanců"),
    "chip_orez":        ("edge trim", "ořez okrajů"),
    "chip_rd":          ("fast decoder", "rychlý dekodér"),
    "chip_pokrocile":   ("advanced…", "pokročilé…"),
    "velikost_odhad":   ("~{0} MB", "~{0} MB"),
    "odkaz_upravit":    ("edit", "upravit"),
    "odkaz_sbalit":     ("collapse", "sbalit"),
    "odkaz_zobrazit":   ("show", "zobrazit"),
    "odkaz_skryt":      ("hide", "skrýt"),
    "pripraveno":       ("Ready to convert", "Připraveno k převodu"),
    "pripraveno_info":  ("{0} · {1} characters · {2} blocks · est. {3}",
                         "{0} · {1} znaků · {2} bloků · odhad {3}"),
    "vyberte_knihu":    ("Choose a book", "Vyberte knihu"),
    "vyberte_knihu_info": ("EPUB, FB2, TXT or HTML. Chapters from EPUB and FB2 become separate files.",
                           "EPUB, FB2, TXT nebo HTML. Kapitoly z EPUB a FB2 budou samostatné soubory."),
    "btn_nacist_jinou": ("Load another book", "Načíst jinou knihu"),
    "btn_vybrat_knihu": ("Choose a book", "Vybrat knihu"),
    "btn_oprava_hotove": ("Fix a passage in a finished book…", "Opravit úsek v hotové knize…"),
    "rozdelane_popis":  ("{0} / {1} blocks · interrupted {2}", "{0} / {1} bloků · přerušeno {2}"),
    "rozdelane_zdroj_chybi": (" · source file missing", " · zdrojový soubor chybí"),
    "btn_pokracovat_kratce": ("Continue", "Pokračovat"),
    "kdy_dnes":         ("today {0}", "dnes {0}"),
    "kdy_vcera":        ("yesterday {0}", "včera {0}"),
    "kdy_datum":        ("{1}/{0} {2}", "{0}. {1}. {2}"),
    "odznak_prevadi":   ("CONVERTING", "PŘEVÁDÍ SE"),
    "odznak_pauza":     ("PAUSED", "POZASTAVENO"),
    "odznak_hotovo":    ("DONE", "HOTOVO"),
    "odznak_zastaveno": ("STOPPED", "ZASTAVENO"),
    "odznak_chyba":     ("FAILED", "CHYBA"),
    "uplynulo":         ("elapsed {0}", "uplynulo {0}"),
    "ulozeno_ve_vystupu": ("saved to the output folder", "uloženo ve výstupu"),
    "lze_navazat":      ("can be resumed later", "lze později navázat"),
    "btn_novy_prevod":  ("New conversion", "Nový převod"),
    "generuje_kapitolu": ("Generating chapter {0} / {1}", "Generuje kapitolu {0} / {1}"),
    "kapitola_x_z":     ("Chapter {0} / {1}", "Kapitola {0} / {1}"),
    "generuje_blok":    ("Generating block {0} / {1}", "Generuje blok {0} / {1}"),
    "bloky_x_z":        ("Blocks {0} / {1}", "Bloky {0} / {1}"),
    "procent_knihy":    ("{0} % of the book", "{0} % knihy"),
    "hotovo_z":         ("Done {0} of {1}", "Hotovo {0} z {1}"),
    "zbyva":            ("Left {0}", "Zbývá {0}"),
    "mapa_kapitol":     ("{0} / {1} chapters", "{0} / {1} kapitol"),
    "btn_zive":         ("Jump to live", "Skočit na živé"),
    "btn_opravit_misto": ("Fix this spot", "Opravit toto místo"),
    "prehravac_prazdny": ("Nothing to play yet", "Zatím není co přehrát"),
    "prehravac_nacita": ("loading…", "načítám…"),
    "vlna_info":        ("chapter {0} · {1}", "kapitola {0} · {1}"),
    "vlna_vygenerovano": (" · generated {0}", " · vygenerováno {0}"),
    "log_souhrn_radek": ("{0} blocks · {1} errors", "{0} bloků · {1} chyb"),
    "log_chyb":         ("{0} errors", "{0} chyb"),
    "filtr_kap_vse":    ("All", "Vše"),
    "filtr_kap_poslech": ("Playable", "K poslechu"),
    "kap_generuje":     ("generating · {0}", "generuje se · {0}"),
    "kapitola_n":       ("Chapter {0}", "Kapitola {0}"),
    "dlg_pokrocile":    ("Advanced settings", "Pokročilé nastavení"),

    # ---------------- Stavy ----------------
    "stav_pripraveno":  ("Ready", "Připraveno"),
    "stav_generuji":    ("Generating audio...", "Generuji audio..."),
    "stav_mp3":         ("Converting to MP3...", "Převádím do MP3..."),
    "stav_chyba":       ("Error", "Chyba"),
    "stav_ukazka":      ("Generating voice sample...", "Generuji ukázku hlasu..."),
    "stav_zastavuji":   ("Stopping after current block...",
                         "Zastavuji po dokončení aktuálního bloku..."),
    "stav_ukoncuji":    ("Finishing - closing the file...",
                         "Ukončuji - dokončuji zápis souboru..."),
    "info_nezdarilo":   ("loading failed", "načtení se nezdařilo"),

    # ---------------- Poslech ----------------

    # ---------------- Dialogy ----------------
    "dlg_chybi_soubor": ("No file", "Chybí soubor"),
    "dlg_vyberte":      ("Select an input file first.", "Nejprve vyberte vstupní soubor."),
    "dlg_chyba_nacteni": ("Loading error", "Chyba při načítání"),
    "dlg_probiha":      ("Conversion running", "Probíhá převod"),
    "dlg_pockejte":     ("Wait until the conversion finishes.", "Počkejte na dokončení převodu."),
    "dlg_chybi_text":   ("No text", "Chybí text"),
    "dlg_zadejte":      ("Enter a test sentence.", "Zadejte testovací větu."),
    "dlg_existuje":     ("File exists", "Soubor existuje"),
    "dlg_prepsat":      ("File already exists:\n{0}\n\nOverwrite?",
                         "Soubor už existuje:\n{0}\n\nPřepsat?"),
    "dlg_ffmpeg":       ("ffmpeg not found", "ffmpeg nenalezen"),
    "dlg_ffmpeg_text":  ("MP3 export needs ffmpeg on PATH.\nOutput will be saved as WAV.",
                         "Pro export do MP3 je potřeba ffmpeg v PATH.\nVýstup bude uložen jako WAV."),
    "dlg_zastavit":     ("Stop", "Zastavit"),
    "dlg_zastavit_text": ("Really stop the conversion?\nWhat has been generated stays saved.",
                          "Opravdu zastavit převod?\nDosud vygenerovaná část zůstane uložena."),
    "dlg_selhal":       ("Conversion failed", "Převod selhal"),
    "dlg_ukoncit":      ("Quit", "Ukončit"),
    "dlg_ukoncit_text": ("A conversion is running. Really quit?\nThe file will be closed properly.",
                         "Probíhá převod. Opravdu ukončit?\nRozpracovaný soubor se ještě korektně uzavře."),
    "dlg_chyba":        ("Error", "Chyba"),
    "dlg_slozka":       ("Could not open the folder:\n{0}", "Složku se nepodařilo otevřít:\n{0}"),
    "err_spoustec":     ("{0} is not in PATH", "{0} není v PATH"),
    "dlg_vyber_knihu":  ("Select an e-book", "Vyberte e-knihu"),
    "dlg_vyber_hlas":   ("Select a reference voice recording", "Vyberte referenční nahrávku hlasu"),
    "dlg_vyber_slozku": ("Select the output folder", "Vyberte výstupní složku"),
    "filtr_vse":        ("All supported", "Všechny podporované"),
    "filtr_text":       ("Text file", "Textový soubor"),
    "filtr_html":       ("HTML", "HTML"),
    "filtr_zvuk":       ("Audio files", "Zvukové soubory"),
    "filtr_vsechny":    ("All files", "Všechny soubory"),

    # ---------------- Log ----------------
    "log_cache":        ("Model cache: {0}", "Cache modelů: {0}"),
    "log_font":         ("Note: JetBrains Mono could not be loaded, using {0}.",
                         "Poznámka: JetBrains Mono se nepodařilo načíst, používám {0}."),
    "log_ffmpeg":       ("Note: ffmpeg not found - MP3 export unavailable.",
                         "Poznámka: ffmpeg nebyl nalezen - export do MP3 nebude dostupný."),
    "log_sd":           ("Note: sounddevice missing - the player is unavailable.",
                         "Poznámka: modul sounddevice chybí - přehrávač nebude dostupný."),
    "log_zarizeni":     ("Device: {0}", "Zařízení: {0}"),
    "log_gpu":          ("GPU: {0} ({1:.1f} GB VRAM)", "GPU: {0} ({1:.1f} GB VRAM)"),
    "log_cuda_ne":      ("WARNING: CUDA unavailable, switching to CPU.",
                         "VAROVÁNÍ: CUDA není dostupná, přepínám na CPU."),
    "log_znovu":        ("Model settings changed, reloading.",
                         "Nastavení modelu se změnilo, načítám model znovu."),
    "log_nacitam":      ("Loading Chatterbox Multilingual (~3 GB downloaded on first run only)...",
                         "Načítám model Chatterbox Multilingual (jen při prvním spuštění se stahuje ~3 GB, pak už z cache)..."),
    "log_nacten":       ("Model loaded. Sample rate: {0} Hz",
                         "Model načten. Vzorkovací frekvence: {0} Hz"),
    "log_jazyk_doplnen": ("Language '{0}' added to the model's allowed list (token [{0}]).",
                          "Jazyk '{0}' doplněn do seznamu povolených jazyků (token [{0}])."),
    "log_bez_ft":       ("Note: no language model is loaded for {0}, using the base weights. "
                         "Pronunciation may be accented.",
                         "Poznámka: pro {0} není načten jazykový model, jedou základní váhy. "
                         "Výslovnost může mít přízvuk."),
    "log_ft_cache":     ("Language model loaded from cache (not downloaded again).",
                         "Jazykový model načten z cache (nestahuje se znovu)."),
    "log_ft_stahuji":   ("Downloading language model: {0} (~{1:.1f} GB), one-off - cached afterwards.",
                         "Stahuji jazykový model: {0} (~{1:.1f} GB), jednorázově - příště se vezme z cache."),
    "log_ft_chyba":     ("WARNING: could not download the language checkpoint: {0}",
                         "VAROVÁNÍ: jazykový checkpoint se nepodařilo stáhnout: {0}"),
    "log_ft_zaklad":    ("Continuing with the base multilingual model.",
                         "Pokračuji se základním multilingválním modelem."),
    "log_ft_nenalezen": ("WARNING: no usable checkpoint found in the repository.",
                         "VAROVÁNÍ: v repozitáři nebyl nalezen použitelný checkpoint."),
    "log_ft_aplikuji":  ("Applying checkpoint: {0}", "Aplikuji checkpoint: {0}"),
    "log_ft_hotovo":    ("Language model applied: {0} tensors ({1}).",
                         "Jazykový model aplikován: {0} tenzorů ({1})."),
    "log_ft_castecne":  ("WARNING: checkpoint only partially matches ({0} unknown, {1} uncovered) - "
                         "if the voice sounds wrong, pick a different language model.",
                         "VAROVÁNÍ: checkpoint sedí jen částečně (nerozpoznaných {0}, nepokrytých {1}) - "
                         "pokud bude hlas divný, zvolte jiný jazykový model."),
    "log_ft_nepovedlo": ("WARNING: could not apply the checkpoint ({0}). Continuing with the base model.",
                         "VAROVÁNÍ: checkpoint se nepodařilo použít ({0}). Pokračuji se základním modelem."),
    "log_lang_ne":      ("WARNING: the model rejected language_id='{0}' ({1}). "
                         "Generating without a language - quality may suffer.",
                         "VAROVÁNÍ: parametr language_id='{0}' model nepřijal ({1}). "
                         "Generuji bez určení jazyka - kvalita může být horší."),
    "log_stahovani":    ("{0}: {1:.2f} GB downloaded ...", "{0}: staženo {1:.2f} GB ..."),
    "log_zaklad_model": ("Base model", "Základní model"),
    "log_ft_popis":     ("Czech fine-tune", "Český fine-tune"),
    "log_nacitam_sbor": ("Loading {0} ...", "Načítám {0} ..."),
    "log_nacteno":      ("Loaded: {0} chars, {1} blocks (max {2} chars per block).",
                         "Načteno: {0} znaků, {1} bloků (max {2} znaků na blok)."),
    "log_ukazka_bloku": ("First block preview: {0}", "Ukázka prvního bloku: {0}"),
    "log_chyba":        ("ERROR: {0}", "CHYBA: {0}"),
    "log_generuji_uk":  ("Generating sample...", "Generuji ukázku..."),
    "log_ukazka_hotova": ("Sample done in {0:.1f} s (length {1:.1f} s): {2}",
                          "Ukázka hotova za {0:.1f} s (délka {1:.1f} s): {2}"),
    "log_chyba_test":   ("ERROR during voice test: {0}", "CHYBA při testu hlasu: {0}"),
    "log_ulozen":       ("File saved: {0}", "Soubor uložen: {0}"),
    "log_start":        ("Conversion started: {0} blocks -> {1}",
                         "Start převodu: {0} bloků -> {1}"),
    "log_orez":         ("Block {1}/{2}: {0:.1f} s of murmur trimmed from the edges.",
                         "Blok {1}/{2}: oříznuto {0:.1f} s brblání na okrajích."),
    "log_rd_stahuji":   ("Downloading the fast decoder ({0:.1f} GB, one time only)...",
                         "Stahuji rychlý dekodér ({0:.1f} GB, jen jednou)..."),
    "log_rd_aktivni":   ("Fast decoder active - 2 steps instead of 10.",
                         "Rychlý dekodér aktivní - 2 kroky místo 10."),
    "err_rd":           ("The fast decoder could not be loaded ({0}). "
                         "Turn it off in advanced settings or try again.",
                         "Rychlý dekodér se nepodařilo načíst ({0}). "
                         "Vypněte ho v pokročilém nastavení, nebo to zkuste znovu."),
    "log_lupance":      ("Block {1}/{2}: {0} click(s) removed from pauses.",
                         "Blok {1}/{2}: {0} lupanec/ů odstraněno z pauz."),
    "log_obalka":       ("Cover generated: {0}", "Obálka vygenerována: {0}"),
    "log_obalka_ne":    ("WARNING: could not generate the cover.",
                         "VAROVÁNÍ: obálku se nepodařilo vygenerovat."),
    "log_zastaveno_na": ("Stopped by user at block {0}/{1}.",
                         "Zastaveno uživatelem na bloku {0}/{1}."),
    "log_prubeh":       ("{0}/{1} blocks  |  audio {2}  |  elapsed {3}  |  left ~{4}",
                         "{0}/{1} bloků  |  audio {2}  |  uplynulo {3}  |  zbývá ~{4}"),
    "log_mp3":          ("Converting output to MP3 (ffmpeg)...",
                         "Převádím výstup do MP3 (ffmpeg)..."),
    "log_mp3_hotovo":   ("MP3 done: {0}", "MP3 hotovo: {0}"),
    "log_mp3_selhal":   ("WARNING: MP3 conversion failed, keeping WAV.",
                         "VAROVÁNÍ: převod do MP3 selhal, zůstává WAV."),
    "log_hotovo":       ("DONE.", "HOTOVO."),
    "log_zastaveno_ul": ("STOPPED - partial file saved.",
                         "ZASTAVENO - uložena rozpracovaná část."),
    "log_souhrn":       (" Audio length {0}, size {1:.1f} MB.",
                         " Délka audia {0}, velikost {1:.1f} MB."),
    "log_neuspesne":    (" Failed blocks: {0}.", " Neúspěšných bloků: {0}."),
    "log_dlouhy":       ("Block {0}/{1}: suspiciously long output ({2:.1f} s for {3} chars), retrying.",
                         "Blok {0}/{1}: podezřele dlouhý výstup ({2:.1f} s pro {3} znaků), generuji znovu."),
    "log_ocas":         ("Block {0}/{1}: the model kept going after the text ended ({2:.1f} s extra).",
                         "Blok {0}/{1}: model po dočtení nepřestal ({2:.1f} s navíc)."),
    "log_nedocteno":    ("Block {0}/{1}: the model did not read the text to the end.",
                         "Blok {0}/{1}: model text nedočetl do konce."),
    "log_pomaly":       ("Block {0}/{1}: read too slowly ({2:.1f} characters per second), probably drawn out by murmur.",
                         "Blok {0}/{1}: čte se moc pomalu ({2:.1f} znaku za sekundu), nejspíš protažený brbláním."),
    "log_ticho":        ("Block {0}/{1}: {2:.1f} s without speech inside the block (murmur).",
                         "Blok {0}/{1}: {2:.1f} s bez řeči uvnitř bloku (brblání)."),
    "log_asr_stahuji":  ("Downloading the transcription check model ({0:.1f} GB, one time only)...",
                         "Stahuji model pro kontrolu přepisem ({0:.1f} GB, jen jednou)..."),
    "log_asr_nacten":   ("Transcription check ready ({0}).", "Kontrola přepisem připravena ({0})."),
    "log_asr_chyba":    ("WARNING: transcription check failed: {0}",
                         "VAROVÁNÍ: kontrola přepisem selhala: {0}"),
    "log_asr_vyber":    ("Block {0}/{1}: transcription picked attempt {2} of {3} (match {4:.0%}).",
                         "Blok {0}/{1}: přepis vybral pokus {2} ze {3} (shoda {4:.0%})."),
    "log_prazdny":      ("Block {0}/{1}: empty output, retrying.",
                         "Blok {0}/{1}: prázdný výstup, opakuji."),
    "log_pokus":        ("Block {0}/{1} - attempt {2} failed: {3}",
                         "Blok {0}/{1} - pokus {2} selhal: {3}"),
    "log_preskocen":    ("Block {0}/{1} SKIPPED: {2}...", "Blok {0}/{1} PŘESKOČEN: {2}..."),
    "log_rozdeleno":    ("Block {0}/{1} kept failing - trying it in {2} shorter parts.",
                         "Blok {0}/{1} opakovaně selhal - zkouším ho po {2} kratších částech."),
    "log_chybejici":    ("WARNING: {0} passage(s) could not be generated and are missing from the audiobook. List: {1}",
                         "VAROVÁNÍ: {0} úsek(ů) se nepodařilo vygenerovat a v audioknize chybí. Seznam: {1}"),
    "soubor_chybejici": (" - missing text.txt", " - chybějící text.txt"),
    "chybejici_hlavicka": ("These passages could not be generated and are missing from the audiobook.",
                           "Tyto úseky se nepodařilo vygenerovat a v audioknize chybí."),
    "chybejici_radek":  ("block {0}, chapter {1}: {2}", "blok {0}, kapitola {1}: {2}"),
    "log_pokracuji":    ("Resuming...", "Pokračuji..."),
    "log_pozastaveno":  ("Paused. Playback keeps draining the buffer, generating is halted.",
                         "Pozastaveno. Přehrávání dobírá zásobu, generování stojí."),
    "log_poslech_chyba": ("PLAYBACK ERROR: {0}", "CHYBA přehrávání: {0}"),
    "log_vyslovnost":   ("Pronunciation dictionary: {0} replacements from {1} rules.",
                         "Slovníček výslovnosti: {0} náhrad podle {1} pravidel."),
    "log_vyslovnost_cs": ("Czech pronunciation from Wiktionary: {0} words marked soft.",
                          "Česká výslovnost z Wikislovníku: {0} slov dostalo háček."),
    "log_kapitoly":     ("Chapters detected: {0}", "Rozpoznáno kapitol: {0}"),
    "log_po_kapitolach": ("Writing one MP3 per chapter ({0} chapters).",
                          "Zapisuji jeden MP3 na kapitolu ({0} kapitol)."),
    "log_kapitola_hotova": ("Chapter {0} done: {1}", "Kapitola {0} hotova: {1}"),
    "log_souhrn_kapitoly": (" {0} chapter files written.", " Zapsáno {0} souborů kapitol."),
    "log_navazuji":     ("Resuming at block {0} of {1}.", "Navazuji od bloku {0} z {1}."),
    "log_navazuji_soubor": ("Continuing file {0}, already {1} of audio.",
                            "Navazuji na soubor {0}, zatím {1} audia."),
    "log_navazuji_zmeny": ("Resuming with changed corrections: {0}.",
                           "Navazuji se změněnými opravami: {0}."),
    "dlg_nelze_navazat": ("Cannot resume", "Nelze navázat"),
    "dlg_nelze_navazat_text": ("This book was interrupted at block {0} of {1}, but it cannot be resumed "
                               "because this changed: {2}.\n\nStart over? Files already generated "
                               "for this book will be overwritten.\n\nNo - leave everything as it is.",
                               "Tato kniha byla přerušena na bloku {0} z {1}, ale navázat nejde, "
                               "protože se změnilo: {2}.\n\nZačít znovu? Už vygenerované soubory "
                               "této knihy se přepíšou.\n\nNe - nechat všechno, jak je."),
    "duvod_neznamy":    ("the book text, its split into blocks or the reference recording",
                         "text knihy, jeho rozdělení na bloky nebo referenční nahrávka"),
    "nazev_hlas":       ("reference voice", "referenční hlas"),
    "nazev_format":     ("output format", "formát výstupu"),
    "nazev_bitrate":    ("MP3 bitrate", "datový tok MP3"),
    "nazev_slovnik":    ("pronunciation dictionary", "slovníček výslovnosti"),
    "log_lze_navazat":  ("Progress saved - you can resume this book later.",
                         "Postup uložen - v knize lze později pokračovat."),
    "log_postup_neplatny": ("A saved progress file exists but the book or settings changed, "
                            "so it cannot be resumed. Starting over.",
                            "Uložený postup existuje, ale kniha nebo nastavení se změnily, "
                            "takže na něj nelze navázat. Začínám znovu."),
    "log_kapitola_rozdelana": ("Chapter left unfinished as {0} - it will be completed on resume.",
                               "Kapitola zůstala rozdělaná jako {0} - dokončí se při navázání."),
    "log_pool_start":   ("Starting {0} generator processes ({1:.1f} GB VRAM free)...",
                         "Spouštím {0} generujících procesů (volných {1:.1f} GB VRAM)..."),
    "log_pool_pripraven": ("{0} processes ready, generating in parallel.",
                           "{0} procesů připraveno, generuji souběžně."),
    "log_pool_selhal":  ("WARNING: parallel generation failed to start ({0}), "
                         "falling back to a single process.",
                         "VAROVÁNÍ: souběžné generování se nepodařilo spustit ({0}), "
                         "pokračuji jedním procesem."),
    "log_pool_jeden":   ("Generating in a single process.", "Generuji jedním procesem."),
    "lab_pracovniku":   ("parallel processes", "souběžných procesů"),
    "log_wav_ponechan": ("Left as {0} - MP3 conversion happens once the book is finished.",
                         "Ponecháno jako {0} - na MP3 se převede až po dokončení knihy."),
    "dlg_navazat":      ("Resume", "Navázat"),
    "dlg_navazat_text": ("This book was interrupted at block {0} of {1} ({2:.0f} %).\n\nYes - continue where it stopped\nNo - start over\nCancel - do nothing",
                         "Tato kniha byla přerušena na bloku {0} z {1} ({2:.0f} %).\n\nAno - pokračovat tam, kde to skončilo\nNe - začít znovu\nZrušit - neprovádět nic"),
    "log_jazyk":        ("Interface language: {0}", "Jazyk rozhraní: {0}"),
}
